// demos/sveltekit-blog/src/routes/drafts/+page.svelte
<script lang="ts">
	import { onDestroy } from 'svelte';
	import { useQuery, useCommand } from '@fougere/svelte';
	import Post from '../../../fronds/blog/entities/Post';

	const drafts = useQuery<Post>(Post, 'listDrafts');
	const publish = useCommand(Post, 'publish');

	// The link needs to forget this read when the page goes. React does it in an
	// effect's teardown, Vue in `onScopeDispose`; Svelte says so out loud.
	onDestroy(() => drafts.dispose());
</script>

<main>
	<h1>Drafts</h1>
	{#if $drafts.loading}<p>Loading…</p>{/if}
	{#if $drafts.error}<p style="color:#b00">{$drafts.error.message}</p>{/if}
	{#if !$drafts.loading && $drafts.items.length === 0}<p>No drafts left — everything is published.</p>{/if}

	{#each $drafts.items as post (post.id)}
		<article style="display:flex;align-items:center;gap:1rem;border-bottom:1px solid #f0f0f0;padding:.75rem 0">
			<div style="flex:1">
				<h2 style="font-size:1.05rem;margin:0">{post.title}</h2>
				<small style="color:#999">{post.status}</small>
			</div>
			<button type="button" disabled={$publish.loading} onclick={() => publish.execute({ params: { id: post.id } })}>
				Publish
			</button>
		</article>
	{/each}

	{#if $publish.error}<p style="color:#b00">{$publish.error.message}</p>{/if}
	<button type="button" onclick={() => drafts.refresh()} style="margin-top:1rem">Refresh</button>
</main>

// demos/next-blog/app/drafts/page.tsx
'use client';

import { useQuery, useCommand } from '@fougere/react';
import Post from '@fronds/blog/entities/Post';

/**
 * The couple. `useQuery(Post, 'listDrafts')` reads, `useCommand(Post, 'publish')`
 * writes, and nothing wires them together: both designate the same entity, so a
 * successful publish revalidates this list on its own.
 *
 * The identical component under Nuxt is the same two lines with `ref`s instead of
 * `useState` — the rules live in `@fougere/app/client`, shared by both.
 */
export default function DraftsPage() {
  const { items, loading, error, refresh } = useQuery<Post>(Post, 'listDrafts');
  const publish = useCommand(Post, 'publish');

  return (
    <main>
      <h1>Drafts</h1>
      {loading && <p>Loading…</p>}
      {error && <p style={{ color: '#b00' }}>{error.message}</p>}
      {!loading && items.length === 0 && <p>No drafts left — everything is published.</p>}

      {items.map((post) => (
        <article key={post.id} style={{ display: 'flex', alignItems: 'center', gap: '1rem', borderBottom: '1px solid #f0f0f0', padding: '0.75rem 0' }}>
          <div style={{ flex: 1 }}>
            <h2 style={{ fontSize: '1.05rem', margin: 0 }}>{post.title}</h2>
            <small style={{ color: '#999' }}>{post.status}</small>
          </div>
          <button
            type="button"
            disabled={publish.loading}
            onClick={() => publish.execute({ params: { id: post.id } })}
          >
            Publish
          </button>
        </article>
      ))}

      {publish.error && <p style={{ color: '#b00' }}>{publish.error.message}</p>}
      <button type="button" onClick={() => void refresh()} style={{ marginTop: '1rem' }}>Refresh</button>
    </main>
  );
}
