// demos/next-blog/app/new/page.tsx
'use client';

import { useRouter } from 'next/navigation';
import { useFormFor } from '@fougere/react';
import Post from '@fronds/blog/entities/Post';

/**
 * The form contract, not a form widget. `fields` comes from the entity's own axes:
 * `status` and `publishedAt` are absent because they are `readOnly` (they are not in
 * `inputFields`), `title` carries `minlength`/`maxlength` from its shape, and the
 * local judge is the same one the handler runs — one declaration, both sides.
 *
 * The page owns every tag below. Fougere states what a field IS; it never renders.
 */
export default function NewPostPage() {
  const router = useRouter();
  const form = useFormFor(Post);

  return (
    <main>
      <h1>New post</h1>
      <form
        onSubmit={async (event) => {
          event.preventDefault();
          const created = await form.submit();
          if (created) router.push('/drafts');
        }}
        style={{ display: 'grid', gap: '1rem', maxWidth: 460 }}
      >
        {form.fields.map((field) => (
          <label key={field.name} style={{ display: 'grid', gap: '0.25rem' }}>
            <span>{field.label}</span>
            <input
              {...field.attrs}
              value={String(form.values[field.name] ?? '')}
              onChange={(event) => form.setValue(field.name, event.target.value)}
            />
            {form.errors[field.name] && (
              <small style={{ color: '#b00' }}>{form.errors[field.name]}</small>
            )}
          </label>
        ))}

        <button type="submit" disabled={form.loading}>
          {form.loading ? 'Saving…' : 'Create draft'}
        </button>
        {form.error && <p style={{ color: '#b00' }}>{form.error.message}</p>}
      </form>

      <p style={{ color: '#999', marginTop: '2rem' }}>
        The form shows {form.fields.length} of the entity's six fields. <code>id</code> and{' '}
        <code>createdAt</code> are filled by the lifecycle axis, <code>status</code> and{' '}
        <code>publishedAt</code> are <code>readOnly</code> — none of the four is a client's to supply.
      </p>
    </main>
  );
}

// demos/sveltekit-blog/src/routes/new/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { useFormFor } from '@fougere/svelte';
	import Post from '../../../fronds/blog/entities/Post';

	const form = useFormFor(Post);
	const { fields, values, errors, command } = form;
</script>

<main>
	<h1>New post</h1>
	<form
		onsubmit={async (event) => {
			event.preventDefault();
			if (await form.submit()) await goto('/drafts');
		}}
		style="display:grid;gap:1rem;max-width:460px"
	>
		{#each fields as field (field.name)}
			<label style="display:grid;gap:.25rem">
				<span>{field.label}</span>
				<input {...field.attrs} bind:value={$values[field.name]} />
				{#if $errors[field.name]}<small style="color:#b00">{$errors[field.name]}</small>{/if}
			</label>
		{/each}

		<button type="submit" disabled={$command.loading}>
			{$command.loading ? 'Saving…' : 'Create draft'}
		</button>
		{#if $command.error}<p style="color:#b00">{$command.error.message}</p>{/if}
	</form>

	<p style="color:#999;margin-top:2rem">
		The form shows {fields.length} of the entity's six fields. <code>id</code> and
		<code>createdAt</code> are filled by the lifecycle axis, <code>status</code> and
		<code>publishedAt</code> are <code>readOnly</code>.
	</p>
</main>
